<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.agilebiz.Sales.DirectSalesReturnScripts" tests="7" time="260.749" ignored="18" failures="6" timestamp="27 Feb 2020 09:12:23 GMT" skipped="0" hostname="Virat-PC" errors="0">
  <testcase name="directSalesReturn" time="29.365" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <failure type="java.lang.AssertionError" message="value cannot be matched expected [ACER LAPTOP  WHITE] but found [APPLE MOBILE JJJ]">
      <![CDATA[java.lang.AssertionError: value cannot be matched expected [ACER LAPTOP  WHITE] but found [APPLE MOBILE JJJ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.agilebiz.Utilities.GenericMethods.addrecordingrid(GenericMethods.java:837)
	at com.agilebiz.Pages.Sales.DirectSalesReturn.validateandsetFillgridItem(DirectSalesReturn.java:119)
	at com.agilebiz.Sales.DirectSalesReturnScripts.directSalesReturn(DirectSalesReturnScripts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- directSalesReturn -->
  <testcase name="directSalesReturn" time="86.024" classname="com.agilebiz.Sales.DirectSalesReturnScripts"/>
  <testcase name="directSalesReturn" time="25.746" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <failure type="java.lang.AssertionError" message="Oops! Values cannot be validated/entered from Fillgrid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Oops! Values cannot be validated/entered from Fillgrid expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at com.agilebiz.Sales.DirectSalesReturnScripts.directSalesReturn(DirectSalesReturnScripts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- directSalesReturn -->
  <testcase name="directSalesReturn" time="37.526" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <failure type="java.lang.AssertionError" message="Values cannot be matched expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: Values cannot be matched expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.agilebiz.Utilities.GenericMethods.addrecordingrid(GenericMethods.java:819)
	at com.agilebiz.Pages.Sales.DirectSalesReturn.validateandsetFillgridItem(DirectSalesReturn.java:119)
	at com.agilebiz.Sales.DirectSalesReturnScripts.directSalesReturn(DirectSalesReturnScripts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- directSalesReturn -->
  <testcase name="directSalesReturn" time="22.510" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <failure type="java.lang.AssertionError" message="Oops! Values cannot be validated/entered from Fillgrid expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Oops! Values cannot be validated/entered from Fillgrid expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at com.agilebiz.Sales.DirectSalesReturnScripts.directSalesReturn(DirectSalesReturnScripts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- directSalesReturn -->
  <testcase name="directSalesReturn" time="29.079" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <failure type="java.lang.AssertionError" message="value cannot be matched expected [ACER LAPTOP  WHITE] but found [APPLE MOBILE JJJ]">
      <![CDATA[java.lang.AssertionError: value cannot be matched expected [ACER LAPTOP  WHITE] but found [APPLE MOBILE JJJ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.agilebiz.Utilities.GenericMethods.addrecordingrid(GenericMethods.java:837)
	at com.agilebiz.Pages.Sales.DirectSalesReturn.validateandsetFillgridItem(DirectSalesReturn.java:119)
	at com.agilebiz.Sales.DirectSalesReturnScripts.directSalesReturn(DirectSalesReturnScripts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- directSalesReturn -->
  <testcase name="directSalesReturn" time="30.499" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <failure type="java.lang.AssertionError" message="value cannot be matched expected [ACER LAPTOP  WHITE] but found [APPLE MOBILE JJJ]">
      <![CDATA[java.lang.AssertionError: value cannot be matched expected [ACER LAPTOP  WHITE] but found [APPLE MOBILE JJJ]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.agilebiz.Utilities.GenericMethods.addrecordingrid(GenericMethods.java:837)
	at com.agilebiz.Pages.Sales.DirectSalesReturn.validateandsetFillgridItem(DirectSalesReturn.java:119)
	at com.agilebiz.Sales.DirectSalesReturnScripts.directSalesReturn(DirectSalesReturnScripts.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- directSalesReturn -->
  <testcase name="LoginTest" classname="com.agilebiz.Sales.DirectSalesScripts">
    <skipped/>
  </testcase> <!-- LoginTest -->
  <testcase name="endTest" classname="com.agilebiz.Utilities.GenericMethods">
    <skipped/>
  </testcase> <!-- endTest -->
  <testcase name="endTest" classname="com.agilebiz.Utilities.GenericMethods">
    <skipped/>
  </testcase> <!-- endTest -->
  <testcase name="endTest" classname="com.agilebiz.Utilities.GenericMethods">
    <skipped/>
  </testcase> <!-- endTest -->
  <testcase name="endTest" classname="com.agilebiz.Utilities.GenericMethods">
    <skipped/>
  </testcase> <!-- endTest -->
  <testcase name="endTest" classname="com.agilebiz.Utilities.GenericMethods">
    <skipped/>
  </testcase> <!-- endTest -->
  <testcase name="endTest" classname="com.agilebiz.Utilities.GenericMethods">
    <skipped/>
  </testcase> <!-- endTest -->
  <testcase name="LoginTest" classname="com.agilebiz.Sales.SalesInvoiceScripts">
    <skipped/>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" classname="com.agilebiz.Sales.SalesOrderScripts">
    <skipped/>
  </testcase> <!-- LoginTest -->
  <testcase name="LoadRepository_and_OpenBrowser" classname="com.agilebiz.Utilities.TestBase">
    <skipped/>
  </testcase> <!-- LoadRepository_and_OpenBrowser -->
  <testcase name="LoadRepository_and_OpenBrowser" classname="com.agilebiz.Utilities.TestBase">
    <skipped/>
  </testcase> <!-- LoadRepository_and_OpenBrowser -->
  <testcase name="LoadRepository_and_OpenBrowser" classname="com.agilebiz.Utilities.TestBase">
    <skipped/>
  </testcase> <!-- LoadRepository_and_OpenBrowser -->
  <testcase name="LoadRepository_and_OpenBrowser" classname="com.agilebiz.Utilities.TestBase">
    <skipped/>
  </testcase> <!-- LoadRepository_and_OpenBrowser -->
  <testcase name="LoadRepository_and_OpenBrowser" classname="com.agilebiz.Utilities.TestBase">
    <skipped/>
  </testcase> <!-- LoadRepository_and_OpenBrowser -->
  <testcase name="LoadRepository_and_OpenBrowser" classname="com.agilebiz.Utilities.TestBase">
    <skipped/>
  </testcase> <!-- LoadRepository_and_OpenBrowser -->
  <testcase name="LoginTest" classname="com.agilebiz.Sales.SalesDeliveryChallanScripts">
    <skipped/>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" classname="com.agilebiz.Sales.DirectSalesReturnScripts">
    <skipped/>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" classname="com.agilebiz.Sales.SalesReturnScripts">
    <skipped/>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- com.agilebiz.Sales.DirectSalesReturnScripts -->
